## Notebook19a

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

In [2]:
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())
pl.Config.set_fmt_str_lengths(1000)

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"

### Small Example

Much of the code itself is already included in this notebook. We are going to go through it slowly and intentionally to understand how to parse text annotations in Python. To start, load the small English spaCy model:

In [3]:
import spacy
nlp = spacy.load("en_core_web_sm")

Next, create a corpus object with a single text. I've filled in one example, but you should use the string that you had for homework.

In [12]:
docs = pl.DataFrame({
    "doc_id": "Example",
    "text": "There was once a boy named Milo who didn't know what to do with himself -- not just sometimes, but always."
})

Now parse the text with the NLP model.

In [13]:
anno = DSText.process(docs, nlp)
print_rows(anno)

shape: (24, 15)
┌─────────┬─────┬─────┬───────────┬───┬────────┬──────────┬──────────┬─────────┐
│ doc_id  ┆ sid ┆ tid ┆ token     ┆ … ┆ dep    ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---     ┆ --- ┆ --- ┆ ---       ┆   ┆ ---    ┆ ---      ┆ ---      ┆ ---     │
│ str     ┆ i64 ┆ i64 ┆ str       ┆   ┆ str    ┆ i64      ┆ str      ┆ str     │
╞═════════╪═════╪═════╪═══════════╪═══╪════════╪══════════╪══════════╪═════════╡
│ Example ┆ 1   ┆ 1   ┆ There     ┆ … ┆ expl   ┆ 2        ┆          ┆ O       │
│ Example ┆ 1   ┆ 2   ┆ was       ┆ … ┆ ROOT   ┆ 2        ┆          ┆ O       │
│ Example ┆ 1   ┆ 3   ┆ once      ┆ … ┆ advmod ┆ 2        ┆          ┆ O       │
│ Example ┆ 1   ┆ 4   ┆ a         ┆ … ┆ det    ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 5   ┆ boy       ┆ … ┆ attr   ┆ 2        ┆          ┆ O       │
│ Example ┆ 1   ┆ 6   ┆ named     ┆ … ┆ acl    ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 7   ┆ Milo      ┆ … ┆ oprd   ┆ 6        ┆ PERSON   ┆ B       │
│ Example ┆ 1   ┆ 8   ┆ who       ┆ … ┆ nsubj  ┆ 11       ┆          ┆ O       │
│ Example ┆ 1   ┆ 9   ┆ did       ┆ … ┆ aux    ┆ 11       ┆          ┆ O       │
│ Example ┆ 1   ┆ 10  ┆ n't       ┆ … ┆ neg    ┆ 11       ┆          ┆ O       │
│ Example ┆ 1   ┆ 11  ┆ know      ┆ … ┆ relcl  ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 12  ┆ what      ┆ … ┆ dobj   ┆ 14       ┆          ┆ O       │
│ Example ┆ 1   ┆ 13  ┆ to        ┆ … ┆ aux    ┆ 14       ┆          ┆ O       │
│ Example ┆ 1   ┆ 14  ┆ do        ┆ … ┆ xcomp  ┆ 11       ┆          ┆ O       │
│ Example ┆ 1   ┆ 15  ┆ with      ┆ … ┆ prep   ┆ 14       ┆          ┆ O       │
│ Example ┆ 1   ┆ 16  ┆ himself   ┆ … ┆ pobj   ┆ 15       ┆          ┆ O       │
│ Example ┆ 1   ┆ 17  ┆ --        ┆ … ┆ punct  ┆ 5        ┆          ┆ O       │
│ Example ┆ 1   ┆ 18  ┆ not       ┆ … ┆ neg    ┆ 20       ┆          ┆ O       │
│ Example ┆ 1   ┆ 19  ┆ just      ┆ … ┆ advmod ┆ 20       ┆          ┆ O       │
│ Example ┆ 1   ┆ 20  ┆ sometimes ┆ … ┆ advmod ┆ 2        ┆          ┆ O       │
│ Example ┆ 1   ┆ 21  ┆ ,         ┆ … ┆ punct  ┆ 20       ┆          ┆ O       │
│ Example ┆ 1   ┆ 22  ┆ but       ┆ … ┆ cc     ┆ 20       ┆          ┆ O       │
│ Example ┆ 1   ┆ 23  ┆ always    ┆ … ┆ conj   ┆ 20       ┆          ┆ O       │
│ Example ┆ 1   ┆ 24  ┆ .         ┆ … ┆ punct  ┆ 2        ┆          ┆ O       │
└─────────┴─────┴─────┴───────────┴───┴────────┴──────────┴──────────┴─────────┘

Compare this to what you did for the homework. Are there any differences?

### Grabbing Some Data

Next, we are going to grab some text data from Wikipedia. I've written a script that called the Wikipedia API to get the text from a page. Here is the function that takes a page name and returns the text.

In [14]:
import re
import requests
from lxml import html

def wiki_get_text(page):
    resp = requests.get(
        "https://en.wikipedia.org/w/api.php",
        params={
            "action": "parse",
            "page": page,
            "prop": "text",
            "format": "json",
        },
        headers={"User-Agent": "MyBot/1.0 (myemail@example.com)"},
    )
    raw_html = resp.json()["parse"]["text"]["*"]
    tree = html.fromstring(raw_html)
    text = " ".join(p.text_content().strip() for p in tree.xpath("//p"))
    text = re.sub(r"\[\d+\]", "", text)

    return text

We can use this inside of a call to `pl.DataFrame` to build a textual corpus object. Here is an example for the data science page. Start with this one and then come back with your own example.

In [21]:
df = pl.DataFrame({
    "doc_id": "Data science",
    "text": wiki_get_text("Data_science")
})
df

ilia_malinin = pl.DataFrame({
    "doc_id": "Ilia Malinin",
    "text": wiki_get_text("Ilia Malinin")
})
ilia_malinin

alysa_liu = pl.DataFrame({
    "doc_id": "Alysa Liu",
    "text": wiki_get_text("Alysa Liu")
})
alysa_liu

shape: (1, 2)
┌───────────┬──────────────────────────────────────────────────────────────────────────────────────┐
│ doc_id    ┆ text                                                                                 │
│ ---       ┆ ---                                                                                  │
│ str       ┆ str                                                                                  │
╞═══════════╪══════════════════════════════════════════════════════════════════════════════════════╡
│ Alysa Liu ┆ Alysa Liu (born August 8, 2005) is an American figure skater. She is the 2026 Winter │
│           ┆ Olympic champion in both women's singles and in the team event, the 2025 World       │
│           ┆ champion, the 2022 World bronze medalist, the 2025–26 Grand Prix Final champion, a   │
│           ┆ two-time Grand Prix medalist, a four-time Challenger Series champion, and a two-time │
│           ┆ U.S. national champion. At the junior level, Liu was the 2020 World Junior bronze    │
│           ┆ medalist, the 2019–20 Junior Grand Prix Final silver medalist, a two-time Junior     │
│           ┆ Grand Prix champion, and the 2018 U.S. junior national champion. In 2019, Liu, then  │
│           ┆ 13, became the youngest-ever U.S. women's national champion. The following year, she │
│           ┆ became the youngest skater to win two senior national titles, the first woman to win │
│           ┆ consecutive U.S. titles since Ashley Wagner in 2012 and 2013 and the first woman to  │
│           ┆ win the junior and senior titles back-to-back since Mirai Nagasu in 2008. Following  │
│           ┆ a period of retirement, she won a world title at the 2025 World Championships, bec…  │
└───────────┴──────────────────────────────────────────────────────────────────────────────────────┘

Once you have the data, you can process it with the NLP annotation:

In [22]:
anno = DSText.process(ilia_malinin, nlp)
anno

anno2 = DSText.process(alysa_liu, nlp)
anno2

shape: (7_805, 15)
┌───────────┬─────┬─────┬───────┬───┬──────────┬──────────┬──────────┬─────────┐
│ doc_id    ┆ sid ┆ tid ┆ token ┆ … ┆ dep      ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---       ┆ --- ┆ --- ┆ ---   ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ str       ┆ i64 ┆ i64 ┆ str   ┆   ┆ str      ┆ i64      ┆ str      ┆ str     │
╞═══════════╪═════╪═════╪═══════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ Alysa Liu ┆ 1   ┆ 1   ┆       ┆ … ┆ dep      ┆ 2        ┆          ┆ O       │
│ Alysa Liu ┆ 1   ┆ 2   ┆ Alysa ┆ … ┆ compound ┆ 3        ┆ PERSON   ┆ B       │
│ Alysa Liu ┆ 1   ┆ 3   ┆ Liu   ┆ … ┆ nsubj    ┆ 11       ┆ PERSON   ┆ I       │
│ Alysa Liu ┆ 1   ┆ 4   ┆ (     ┆ … ┆ punct    ┆ 3        ┆          ┆ O       │
│ Alysa Liu ┆ 1   ┆ 5   ┆ born  ┆ … ┆ acl      ┆ 3        ┆          ┆ O       │
│ …         ┆ …   ┆ …   ┆ …     ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ Alysa Liu ┆ 332 ┆ 7   ┆ of    ┆ … ┆ prep     ┆ 6        ┆          ┆ O       │
│ Alysa Liu ┆ 332 ┆ 8   ┆ manga ┆ … ┆ pobj     ┆ 7        ┆          ┆ O       │
│ Alysa Liu ┆ 332 ┆ 9   ┆ and   ┆ … ┆ cc       ┆ 8        ┆          ┆ O       │
│ Alysa Liu ┆ 332 ┆ 10  ┆ anime ┆ … ┆ conj     ┆ 8        ┆          ┆ O       │
│ Alysa Liu ┆ 332 ┆ 11  ┆ .     ┆ … ┆ punct    ┆ 2        ┆          ┆ O       │
└───────────┴─────┴─────┴───────┴───┴──────────┴──────────┴──────────┴─────────┘

1. Now, for a little work on your end. Using the code that was in the book, find the top 10 most common nouns on the page.

In [23]:
(
    anno2
    .filter(c.upos == "NOUN")
    .group_by(c.lemma)
    .agg(count = pl.len())
    .sort(c.count, descending=True)
    .head(10)
)

shape: (10, 2)
┌─────────────┬───────┐
│ lemma       ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ program     ┆ 66    │
│ point       ┆ 39    │
│ skate       ┆ 30    │
│ competition ┆ 26    │
│ jump        ┆ 24    │
│ skater      ┆ 23    │
│ woman       ┆ 23    │
│ skating     ┆ 22    │
│ score       ┆ 21    │
│ place       ┆ 19    │
└─────────────┴───────┘

2. And then find the top ten common adjectives.

In [24]:
(
    anno2
    .filter(c.upos == "ADJ")
    .group_by(c.lemma)
    .agg(count = pl.len())
    .sort(c.count, descending=True)
    .head(10)
)

shape: (10, 2)
┌──────────┬───────┐
│ lemma    ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ triple   ┆ 68    │
│ first    ┆ 43    │
│ short    ┆ 37    │
│ free     ┆ 35    │
│ american ┆ 16    │
│ second   ┆ 15    │
│ good     ┆ 15    │
│ female   ┆ 12    │
│ senior   ┆ 12    │
│ young    ┆ 11    │
└──────────┴───────┘

Go back and choose another page and see how the outputs change. Then, wait for use to come together for the next step.

### Sheets

Next we are going to create a class dataset. Once that is finished, we will use the code below to read it in.

In [27]:
SHEET_ID = "1yyeOB8AcNvoDhSoMbjEEkaKKw6REXLV-mH4oJpg0qB8"
GID = "0"

url = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"
url

class_df = pl.read_csv(url)
class_df

shape: (100, 4)
┌───────────────┬──────────────────┬─────────────────────────────┬────────────┐
│ state         ┆ name             ┆ page                        ┆ party      │
│ ---           ┆ ---              ┆ ---                         ┆ ---        │
│ str           ┆ str              ┆ str                         ┆ str        │
╞═══════════════╪══════════════════╪═════════════════════════════╪════════════╡
│ Alabama       ┆ Tommy Tuberville ┆ Tommy_Tuberville            ┆ Republican │
│ Alabama       ┆ Katie Britt      ┆ Katie_Britt                 ┆ Republican │
│ Alaska        ┆ Lisa Murkowski   ┆ Lisa_Murkowski              ┆ Republican │
│ Alaska        ┆ Dan Sullivan     ┆ Dan_Sullivan_(U.S._senator) ┆ Republican │
│ Arizona       ┆ Mark Kelly       ┆ Mark_Kelly                  ┆ Democratic │
│ …             ┆ …                ┆ …                           ┆ …          │
│ West Virginia ┆ Jim Justice      ┆ Jim_Justice                 ┆ Republican │
│ Wisconsin     ┆ Ron Johnson      ┆ Ron_Johnson                 ┆ Republican │
│ Wisconsin     ┆ Tammy Baldwin    ┆ Tammy_Baldwin               ┆ Democratic │
│ Wyoming       ┆ John Barrasso    ┆ John_Barrasso               ┆ Republican │
│ Wyoming       ┆ Cynthia Lummis   ┆ Cynthia_Lummis              ┆ Republican │
└───────────────┴──────────────────┴─────────────────────────────┴────────────┘

Then, we can cycle through the rows of the dataset, putting together the Wikipedia data from each row, and then create a corpus object.

In [28]:

wiki_df = []
for row in class_df.iter_rows(named=True):
    wiki_df.append(pl.DataFrame({
        "doc_id": row['name'],
        "text": wiki_get_text(row['page'])
    }))

wiki_df = pl.concat(wiki_df)
wiki_df

shape: (100, 2)
┌──────────────────┬───────────────────────────────────────────────────────────────────────────────┐
│ doc_id           ┆ text                                                                          │
│ ---              ┆ ---                                                                           │
│ str              ┆ str                                                                           │
╞══════════════════╪═══════════════════════════════════════════════════════════════════════════════╡
│ Tommy Tuberville ┆ Thomas Hawley Tuberville (/ˈtʌbərvɪl/; TUH-bərv-il; born September 18, 1954)  │
│                  ┆ is an American politician, and retired college football coach and sports      │
│                  ┆ broadcaster who is the senior United States senator from Alabama, a seat he   │
│                  ┆ has held since 2021. He is a member of the Republican Party. Before entering  │
│                  ┆ politics, Tuberville was the head football coach at Auburn University from    │
│                  ┆ 1999 to 2008. He was also the head football coach at the University of        │
│                  ┆ Mississippi from 1995 to 1998, Texas Tech University from 2010 to 2012, and   │
│                  ┆ the University of Cincinnati from 2013 to 2016. Tuberville won five national  │
│                  ┆ coach-of-the-year awards (AP, AFCA, Sporting News, Walter Camp, and Bear      │
│                  ┆ Bryant) after Auburn's 13–0 season in 2004, in which Auburn won the           │
│                  ┆ Southeastern Conference title and the Sugar Bowl, but was left out of the BCS │
│                  ┆ National Championship Game. He earned his 100th career win in 2007.           │
│                  ┆ Tuberville is the only Auburn football coach to beat in-state rival Alabama   │
│                  ┆ six consecutive times. In 2015, he…                                           │
│ Katie Britt      ┆ Katie Elizabeth Boyd Britt (née Boyd; born February 2, 1982) is an American   │
│                  ┆ politician and attorney serving since 2023 as the junior United States        │
│                  ┆ senator from Alabama. A member of the Republican Party, Britt is the first    │
│                  ┆ woman to be elected to the U.S. Senate from Alabama and the youngest          │
│                  ┆ Republican woman to be elected to the Senate. She was president and CEO of    │
│                  ┆ the Business Council of Alabama from 2019 to 2021, and served as chief of     │
│                  ┆ staff for the previous incumbent, Richard Shelby, from 2016 to 2018. Britt    │
│                  ┆ was born Katie Elizabeth Boyd on February 2, 1982, to Julian and Debra Boyd   │
│                  ┆ in Enterprise, Alabama. During her youth she worked at her family's business. │
│                  ┆ Her family lived near Fort Rucker in Dale County, Alabama. Her father owned a │
│                  ┆ hardware store and later a boat dealership; her mother owned a dance studio.  │
│                  ┆ A graduate of Enterprise High School, Britt was a cheerleader and a           │
│                  ┆ valedictorian. After graduating in 2000 she studied political science at the  │
│                  ┆ University of Alabama. She was…                                               │
│ Lisa Murkowski   ┆  Lisa Ann Murkowski (/mərˈkaʊski/                                             │
│                  ┆ mər-KOW-ski; born May 22, 1957) is an American attorney and politician        │
│                  ┆ serving as the senior United States senator from the state of Alaska, having  │
│                  ┆ held the seat since 2002. She is the first woman to represent Alaska in the   │
│                  ┆ U.S. Congress and is the Senate's second-most senior Republican woman.        │
│                  ┆ Murkowski became dean of Alaska's congressional delegation upon               │
│                  ┆ Representative Don Young's death. Murkowski is the daughter of former U.S.    │
│                  ┆ senator and governor of Alaska Frank Murkowski. She was appointed to the      │
│                  ┆ Senate by her father, who resigned his seat in 2002 to become Alaska's        │
│                  ┆ governor. Murkowski became the first Alaskan-born member of Congress and      │
│                  ┆ completed her father's unexpired Senate term, which ended in January 2005.    │
│                  ┆ Before her appointment to the Senate, she had been a member of the Alaska     │
│                  ┆ House of Representatives since 1999. Murkowski ran for and won a full term in │
│                  ┆ 2004 with 48% of the vote. After losing the 2010 Republican primary to Tea    │
│                  ┆ Party candida…                                                                │
│ Dan Sullivan     ┆ Daniel Scott Sullivan (born November 13, 1964) is an American politician,     │
│                  ┆ attorney, and Marine Corps veteran serving as the junior United States        │
│                  ┆ senator from the state of Alaska since 2015. A member of the Republican       │
│                  ┆ Party, Sullivan previously served as the commissioner of the Alaska           │
│                  ┆ Department of Natural Resources from 2010 to 2013, and as the Alaska Attorney │
│                  ┆ General from 2009 to 2010. Sullivan grew up in a suburb of Cleveland, Ohio    │
│                  ┆ and graduated from Culver Academies in Indiana. He studied economics at       │
│                  ┆ Harvard University, then earned joint foreign service and Juris Doctor        │
│                  ┆ degrees from Georgetown University. He was on active duty for the United      │
│                  ┆ States Marine Corps from 1993 to 1997, 2004 to 2006, and in 2009 and 2013.    │
│                  ┆ Between 1997 and 1999, he clerked for judges on the United States Court of    │
│                  ┆ Appeals for the Ninth Circuit and the Alaska Supreme Court. He worked as an   │
│                  ┆ attorney in private practice in Anchorage, Alaska, from 2000 to 2002.         │
│                  ┆ Sullivan moved to Washington, DC to work for the …                            │
│ Mark Kelly       ┆ Mark Edward Kelly (born February 21, 1964) is an American politician and a    │
│                  ┆ retired astronaut and naval officer. He is the senior United States senator   │
│                  ┆ from Arizona, a seat he has held since 2020. He is a member of the Democratic │
│                  ┆ Party. Kelly flew combat missions during the Gulf War as a naval aviator      │
│                  ┆ before being selected as a NASA Space Shuttle pilot in 1996. His identical    │
│                  ┆ twin brother, Scott Kelly, also became a NASA astronaut that year. Mark flew  │
│                  ┆ his first space mission in 2001 as pilot of STS-108, then piloted STS-121 in  │
│                  ┆ 2006, and commanded STS-124 in 2008 and STS-134 (the final mission of Space   │
│                  ┆ Shuttle Endeavour) in 2011. In January 2011, Kelly's wife, then-Arizona       │
│                  ┆ Representative Gabby Giffords, was shot and nearly killed in an assassination │
│                  ┆ attempt in Arizona. Kelly retired from the Navy and NASA that October. In     │
│                  ┆ 2013, Kelly and Giffords founded a nonprofit political action committee,      │
│                  ┆ Americans for Responsible Solutions (later merged into Giffords), which       │
│                  ┆ campaigned for gun cont…                                                      │
│ …                ┆ …                                                                             │
│ Jim Justice      ┆ James Conley Justice II (born April 27, 1951) is an American politician and   │
│                  ┆ businessman serving since 2025 as the junior United States senator from West  │
│                  ┆ Virginia. A member of the Republican Party, he served from 2017 to 2025 as    │
│                  ┆ the 36th governor of West Virginia. Justice was once a billionaire, but his   │
│                  ┆ net worth was estimated to $664.2 million in 2025, making him the richest     │
│                  ┆ U.S. senator as of that year. He inherited a coal mining business from his    │
│                  ┆ father that included 94 companies. He and his family own the Greenbrier, a    │
│                  ┆ luxury resort and National Historic Landmark in White Sulphur Springs. In     │
│                  ┆ 2015, Justice announced his candidacy for governor in 2016. Although a        │
│                  ┆ registered Republican before running for governor, he ran as a Democrat and   │
│                  ┆ defeated the Republican nominee, Bill Cole. Less than seven months after      │
│                  ┆ taking office, Justice switched back to the Republican Party after announcing │
│                  ┆ his plans at a rally with President Donald Trump in the state. He was         │
│                  ┆ reelected in 2020. Justice wa…                                                │
│ Ron Johnson      ┆ Ronald Harold Johnson (born April 8, 1955) is an American businessman and     │
│                  ┆ politician serving as the senior United States senator from Wisconsin, a seat │
│                  ┆ he has held since 2011. A Republican, Johnson was first elected to the U.S.   │
│                  ┆ Senate in 2010, defeating Democratic incumbent Russ Feingold. He was          │
│                  ┆ reelected in 2016, defeating Feingold in a rematch, and in 2022, narrowly     │
│                  ┆ defeating Lieutenant Governor Mandela Barnes. Before entering politics, he    │
│                  ┆ was chief executive officer of a plastics manufacturer in Oshkosh, Wisconsin. │
│                  ┆ Johnson entered politics to oppose the Affordable Care Act and credits the    │
│                  ┆ Tea Party movement with his political ascent, though he does not personally   │
│                  ┆ identify with the movement. As a freshman senator, he gained a reputation for │
│                  ┆ opposing government spending and seeking a balanced budget, and he has        │
│                  ┆ stalled or voted against budget proposals from both major parties for not     │
│                  ┆ offsetting spending. He is also critical of the Social Security program and   │
│                  ┆ has called for its partia…                                                    │
│ Tammy Baldwin    ┆ Tammy Suzanne Green Baldwin (born February 11, 1962) is an American           │
│                  ┆ politician and lawyer serving since 2013 as the junior United States senator  │
│                  ┆ from Wisconsin. A member of the Democratic Party, she has also served as the  │
│                  ┆ secretary of the Senate Democratic Caucus since 2017. Baldwin has been the    │
│                  ┆ dean of the United States congressional delegation from Wisconsin since 2023, │
│                  ┆ when Representative Ron Kind retired. Baldwin graduated from Smith College    │
│                  ┆ and the University of Wisconsin Law School, and was a lawyer in private       │
│                  ┆ practice before entering the Wisconsin State Assembly in 1993. She served     │
│                  ┆ three terms from Wisconsin's 78th Assembly district from 1993 to 1999, and    │
│                  ┆ seven terms as the United States congresswoman from Wisconsin's 2nd           │
│                  ┆ congressional district from 1999 to 2013. She was elected to the United       │
│                  ┆ States Senate in 2012, and reelected in 2018 and 2024. Baldwin is the first   │
│                  ┆ openly lesbian woman elected to the Wisconsin State Assembly (1993), the      │
│                  ┆ first openly lesbian woman and first wo…                                      │
│ John Barrasso    ┆ John Anthony Barrasso III (/bəˈrɑːsoʊ/ bə-RAH-soh; born July 21, 1952) is an  │
│                  ┆ American physician and politician serving as the senior United States senator │
│                  ┆ from Wyoming, a seat he has held since 2007. A member of the Republican       │
│                  ┆ Party, he served in the Wyoming State Senate from 2003 to 2007. In 2025, he   │
│                  ┆ became Senate majority whip, the second-ranking Senate Republican. Born and   │
│                  ┆ raised in Reading, Pennsylvania, Barrasso graduated from Georgetown           │
│                  ┆ University, where he received his B.S. and M.D. He conducted his medical      │
│                  ┆ residency at Yale University before moving to Wyoming and beginning a private │
│                  ┆ orthopedics practice in Casper. Barrasso first ran for U.S. Senate in 1996,   │
│                  ┆ narrowly losing the Republican primary to Mike Enzi. In 2002, he was elected  │
│                  ┆ to the State Senate, where he stayed until his appointment to the U.S. Senate │
│                  ┆ after the 2007 death of incumbent Craig L. Thomas. He was elected to finish   │
│                  ┆ Thomas's term in 2008, and was reelected in 2012. In 2018, Barrasso was       │
│                  ┆ selected as chair of t…                                                       │
│ Cynthia Lummis   ┆ Cynthia Marie Lummis Wiederspahn (/ˈlʌmɪs/ LUH-miss; born September 10, 1954) │
│                  ┆ is an American attorney and politician serving as the junior United States    │
│                  ┆ senator from Wyoming since 2021. A member of the Republican Party, Lummis     │
│                  ┆ served as the U.S. representative for Wyoming's at-large congressional        │
│                  ┆ district from 2009 to 2017. She served in the Wyoming House of                │
│                  ┆ Representatives from 1979 to 1983 and from 1985 to 1993, in the Wyoming       │
│                  ┆ Senate from 1993 to 1995, and as the Wyoming State Treasurer from 1999 to     │
│                  ┆ 2007. Lummis was elected treasurer of Wyoming in 1998 and reelected without   │
│                  ┆ opposition in 2002. She managed the gubernatorial campaigns of Mary Mead in   │
│                  ┆ 1990 and Ray Hunkins in 2006. She also served on Bob Dole's presidential      │
│                  ┆ steering committee in Wyoming and chaired Mitt Romney's 2012 presidential     │
│                  ┆ campaign in Wyoming. Lummis unsuccessfully sought to be appointed to replace  │
│                  ┆ Senator Craig L. Thomas in 2007. She was elected to succeed Barbara Cubin in  │
│                  ┆ the U.S. House of Representatives in th…                                      │
└──────────────────┴───────────────────────────────────────────────────────────────────────────────┘

As before, we will next create an annotation object.

In [30]:
anno = DSText.process(wiki_df, nlp)
anno

shape: (503_376, 15)
┌──────────────────┬─────┬─────┬────────────┬───┬──────────┬──────────┬──────────┬─────────┐
│ doc_id           ┆ sid ┆ tid ┆ token      ┆ … ┆ dep      ┆ head_idx ┆ ent_type ┆ ent_iob │
│ ---              ┆ --- ┆ --- ┆ ---        ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---     │
│ str              ┆ i64 ┆ i64 ┆ str        ┆   ┆ str      ┆ i64      ┆ str      ┆ str     │
╞══════════════════╪═════╪═════╪════════════╪═══╪══════════╪══════════╪══════════╪═════════╡
│ Tommy Tuberville ┆ 1   ┆ 1   ┆            ┆ … ┆ dep      ┆ 2        ┆          ┆ O       │
│ Tommy Tuberville ┆ 1   ┆ 2   ┆ Thomas     ┆ … ┆ compound ┆ 4        ┆ PERSON   ┆ B       │
│ Tommy Tuberville ┆ 1   ┆ 3   ┆ Hawley     ┆ … ┆ compound ┆ 4        ┆ PERSON   ┆ I       │
│ Tommy Tuberville ┆ 1   ┆ 4   ┆ Tuberville ┆ … ┆ nsubj    ┆ 14       ┆ PERSON   ┆ I       │
│ Tommy Tuberville ┆ 1   ┆ 5   ┆ (          ┆ … ┆ punct    ┆ 4        ┆          ┆ O       │
│ …                ┆ …   ┆ …   ┆ …          ┆ … ┆ …        ┆ …        ┆ …        ┆ …       │
│ Cynthia Lummis   ┆ 184 ┆ 13  ┆ Synod      ┆ … ┆ appos    ┆ 10       ┆          ┆ O       │
│ Cynthia Lummis   ┆ 184 ┆ 14  ┆ (          ┆ … ┆ punct    ┆ 13       ┆          ┆ O       │
│ Cynthia Lummis   ┆ 184 ┆ 15  ┆ LCMS       ┆ … ┆ appos    ┆ 13       ┆          ┆ O       │
│ Cynthia Lummis   ┆ 184 ┆ 16  ┆ )          ┆ … ┆ punct    ┆ 13       ┆          ┆ O       │
│ Cynthia Lummis   ┆ 184 ┆ 17  ┆ .          ┆ … ┆ punct    ┆ 2        ┆          ┆ O       │
└──────────────────┴─────┴─────┴────────────┴───┴──────────┴──────────┴──────────┴─────────┘

3. Adapting the code show in the text, find the 8 nouns that are the most common on each page and print out the results to have a summary of the themes of each page. What patterns do you see? Are there any challenges? What else might you want to do with this data?

In [32]:
(
    anno
    .filter(c.upos == "NOUN")
    .group_by([c.doc_id, c.lemma])
    .agg(count = pl.len())
    .sort([c.doc_id, c.count], descending=[False, True])
    .group_by(c.doc_id)
    .head(8)
    .group_by(c.doc_id)
    .agg(top_adj = c.lemma.sort().str.join("; "))
    .pipe(print_rows)
)

shape: (100, 2)
┌────────────────────────┬─────────────────────────────────────────────────────────────────────────┐
│ doc_id                 ┆ top_adj                                                                 │
│ ---                    ┆ ---                                                                     │
│ str                    ┆ str                                                                     │
╞════════════════════════╪═════════════════════════════════════════════════════════════════════════╡
│ John Boozman           ┆ %; bill; election; legislation; member; senator; term; vote             │
│ John Norvell           ┆ brother; daughter; member; newspaper; son; state; wife; year            │
│ Jim Risch              ┆ bill; election; governor; gun; lieutenant; senator; state; vote         │
│ Martin Heinrich        ┆ %; district; election; legislation; member; senator; state; term        │
│ John Kennedy           ┆ bill; company; law; money; people; state; treasurer; vote               │
│ Mike Lee               ┆ %; bill; election; government; senator; state; vote; waste              │
│ Chris Coons            ┆ %; coon; country; election; letter; office; senator; year               │
│ Mark Kelly             ┆ crew; day; gun; mission; space; station; time; wife                     │
│ Ed Markey              ┆ %; bill; community; election; letter; member; senator; vote             │
│ Brian Schatz           ┆ %; governor; gun; nomination; nominee; right; senator; vote             │
│ Rand Paul              ┆ bill; campaign; election; father; senator; spending; state; year        │
│ Dave McCormick         ┆ -; administration; campaign; policy; position; president; world; year   │
│ Jim Justice            ┆ bill; business; coal; election; governor; justice; law; state           │
│ Chris Murphy           ┆ bill; health; law; legislation; member; senator; shooting; state        │
│ Bernie Sanders         ┆ %; bill; campaign; candidate; election; people; sander; vote            │
│ Patty Murray           ┆ %; bill; election; letter; member; senator; term; year                  │
│ Tom Cotton             ┆ %; administration; bill; election; law; letter; senator; year           │
│ Jacky Rosen            ┆ %; court; letter; nomination; senator; source; time; vote               │
│ Mitch McConnell        ┆ %; election; judge; leader; president; senator; vote; year              │
│ Richard Blumenthal     ┆ attorney; law; letter; member; senator; service; state; year            │
│ Adam Schiff            ┆ district; election; impeachment; manager; member; trial; vote; war      │
│ Bill Cassidy           ┆ %; bill; cassidy; child; election; health; legislation; vote            │
│ Shelley Moore Capito   ┆ %; abortion; bill; funding; legislation; nominee; senator; state        │
│ Susan Collins          ┆ %; bill; election; law; legislation; senator; support; vote             │
│ Lucius Lyon            ┆ admission; city; land; member; part; state; statehood; village          │
│ Lisa Murkowski         ┆ %; campaign; election; nominee; seat; senator; time; vote               │
│ Cynthia Lummis         ┆ campaign; candidate; election; legislation; nominee; reelection; state; │
│                        ┆ tenure                                                                  │
│ Eric Schmitt           ┆ attorney; case; covid-19; general; law; office; state; tax              │
│ John Cornyn            ┆ bill; cornyn; election; law; senator; state; vote; year                 │
│ Maria Cantwell         ┆ %; campaign; debate; election; privacy; senator; state; vote            │
│ Joni Ernst             ┆ bill; campaign; law; senator; state; support; vote; year                │
│ Chuck Schumer          ┆ %; administration; bill; election; government; legislation; senator;    │
│                        ┆ vote                                                                    │
│ Peter Welch            ┆ %; candidate; election; law; member; nominee; seat; vote                │
│ Tim Sheehy             ┆ cattle; company; duty; house; plane; senator; service; wildfire         │
│ Elizabeth Warren       ┆ %; administration; bankruptcy; campaign; candidate; election; family;   │
│                        ┆ law                                                                     │
│ Ashley Moody           ┆ attorney; ballot; cannabis; court; election; general; lawsuit; measure  │
│ Dick Durban            ┆ bill; law; letter; member; program; resolution; senator; year           │
│ Alex Padilla           ┆ %; ballot; election; legislation; president; senator; state; term       │
│ Josh Hawley            ┆ attorney; campaign; election; investigation; law; senator; state; vote  │
│ Raphael Warnock        ┆ bill; campaign; church; election; pastor; right; state; warnock         │
│ Sheldon Whitehouse     ┆ bill; climate; club; member; money; office; state; whitehouse           │
│ Ben Ray Luján          ┆ %; bill; district; election; legislation; nominee; reelection; vote     │
│ Deb Fischer            ┆ %; campaign; county; election; land; law; senator; vote                 │
│ Tim Kaine              ┆ %; administration; election; governor; letter; senator; state; year     │
│ Katie Britt            ┆ bill; border; election; medium; office; president; senator; woman       │
│ Tina Smith             ┆ administration; campaign; election; governor; letter; president;        │
│                        ┆ senator; state                                                          │
│ Angela Alsobrooks      ┆ attorney; bill; campaign; county; election; executive; program; state   │
│ Steve Daines           ┆ %; bill; daine; election; president; seat; senator; vote                │
│ Tammy Duckworth        ┆ %; bill; duckworth; senator; service; veteran; vote; woman              │
│ Cindy Hyde-Smith       ┆ %; bill; election; office; senator; state; time; vote                   │
│ Thom Tillis            ┆ %; bill; election; law; people; senator; state; year                    │
│ John Thune             ┆ %; election; leader; race; senator; vote; whip; year                    │
│ Jon Ossoff             ┆ campaign; candidate; district; election; office; percent; senator; vote │
│ Lyman R. Casey         ┆ business; casey; chairman; commissioner; education; inventor; parent;   │
│                        ┆ renomination                                                            │
│ Kirsten Gillibrand     ┆ %; bill; campaign; election; member; senator; term; year                │
│ Cory Booker            ┆ %; campaign; city; election; mayor; senator; vote; year                 │
│ Mazie Hirono           ┆ %; candidate; district; election; governor; senator; term; vote         │
│ Bernie Moreno          ┆ abortion; campaign; citizenship; dealership; election; interview;       │
│                        ┆ senator; support                                                        │
│ Todd Young             ┆ %; bill; election; legislation; member; rating; seat; senator           │
│ Gilbert A. Pierce      ┆ bill; capital; law; member; newspaper; office; state; time              │
│ Angus King             ┆ %; bill; election; governor; legislation; senator; state; vote          │
│ John Barrasso          ┆ %; bill; climate; election; member; primary; time; vote                 │
│ Maggie Hassan          ┆ %; campaign; governor; law; position; senator; state; year              │
│ Marsha Blackburn       ┆ bill; blackburn; child; election; member; senator; state; woman         │
│ James Lankford         ┆ %; bill; election; marriage; senator; sex; state; vote                  │
│ John Hickenlooper      ┆ %; bill; campaign; city; governor; hickenlooper; mayor; state           │
│ Jerry Moran            ┆ %; bill; law; legislation; member; senator; state; vote                 │
│ Chuck Grassley         ┆ bill; health; law; legislation; senator; tax; vote; year                │
│ Dan Sullivan           ┆ %; election; law; office; project; race; state; vote                    │
│ Markwayne Mullin       ┆ %; citizen; election; member; runoff; senator; term; vote               │
│ Ted Cruz               ┆ %; campaign; election; government; law; senator; state; vote            │
│ Ron Wyden              ┆ bill; government; law; legislation; letter; senator; tax; year          │
│ John Fettermen         ┆ election; governor; lieutenant; mayor; senator; stroke; town; vote      │
│ Ted Budd               ┆ %; bill; district; election; home; member; senator; vote                │
│ Mike Rounds            ┆ %; election; government; investment; member; nomination; round; state   │
│ Ruben Gallego          ┆ %; campaign; election; group; member; organization; state; vote         │
│ Tim Scott              ┆ %; bill; county; district; election; member; seat; senator              │
│ Tommy Tuberville       ┆ coach; football; head; record; season; senator; team; year              │
│ Rick Scott             ┆ %; company; election; governor; law; school; state; voting              │
│ Jeanne Shaheen         ┆ %; bill; campaign; governor; senator; state; tax; term                  │
│ Lindsey Graham         ┆ %; election; nominee; president; senator; state; vote; war              │
│ Michael Bennet         ┆ administration; child; election; law; letter; member; senator; year     │
│ Bill Hagerty           ┆ ambassador; campaign; director; election; equity; firm; investment;     │
│                        ┆ vote                                                                    │
│ Tammy Baldwin          ┆ %; bill; care; health; letter; senator; state; vote                     │
│ Jack Reed              ┆ %; district; election; position; right; senator; term; trade            │
│ Pete Ricketts          ┆ %; bill; election; governor; legislature; session; state; tax           │
│ Mark Warner            ┆ %; bill; governor; member; senator; state; vote; year                   │
│ Roger Marshall         ┆ %; aid; district; election; primary; senator; state; vote               │
│ Catherine Cortez Masto ┆ %; action; attorney; general; office; senator; state; vote              │
│ Roger Wicker           ┆ %; bill; district; election; member; nominee; state; vote               │
│ Chris Van Hollen       ┆ %; bill; district; election; member; part; tax; vote                    │
│ Andy Kim               ┆ %; ballot; campaign; county; district; election; primary; vote          │
│ John Curtis            ┆ %; bill; business; election; land; legislation; member; vote            │
│ Jon Husted             ┆ business; election; hour; office; state; term; voter; year              │
│ Amy Klobuchar          ┆ %; attorney; campaign; candidate; election; law; senator; vote          │
│ Jim Banks              ┆ %; bank; duty; election; member; people; senator; state                 │
│ Lisa Blunt Rochester   ┆ %; district; election; mask; member; nominee; secretary; woman          │
│ Jeff Merkley           ┆ administration; bill; law; legislation; letter; program; senator; year  │
│ Mike Crapo             ┆ %; bill; gun; law; nominee; senator; term; vote                         │
│ Ron Johnson            ┆ %; campaign; election; government; investigation; position; spending;   │
│                        ┆ support                                                                 │
└────────────────────────┴─────────────────────────────────────────────────────────────────────────┘